/**
 * Verbwire API documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body17 model module.
* @module model/Body17
* @version 1.0.0
*/
export default class Body17 {
    /**
    * Constructs a new <code>Body17</code>.
    * @alias module:model/Body17
    * @class
    * @param transactionId {String} 
    */

    constructor(transactionId) {
        
        
        this['transactionId'] = transactionId;
        
    }

    /**
    * Constructs a <code>Body17</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body17} obj Optional instance to populate.
    * @return {module:model/Body17} The populated <code>Body17</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body17();
                        
            
            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} transactionId
    */
    'transactionId' = undefined;




}
